project_id = "fxolgklxzibbakbrokcn"

[functions.bedrock-chat]
verify_jwt = false

[functions.send-appointment-sms]
verify_jwt = false

[functions.send-patient-links]
verify_jwt = true

[functions.openai-chat]
verify_jwt = false

[functions.send-validation-sms]
verify_jwt = false

[functions.relay-aws-agent]
verify_jwt = false