// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxolgklxzibbakbrokcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4b2xna2x4emliYmFrYnJva2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjAwODUsImV4cCI6MjA2OTgzNjA4NX0.O4SoHaTTa3Z7KhmsUGmavoaH-WtCbd2V6uenj_hPMN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});